### ISSUE TITLE
Everpad 2.5 doesn't start: pkg_resources.DistributionNotFound: py-oauth2

### ISSUE THREAD

**Issue by hotice** [nvbn/everpad#261]
The latest Everpad 2.5 doesn't start (using the PPA in Ubuntu 12.10):

Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2803, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 696, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: py-oauth2

Let me know if you need more info.

Also, I see the Raring packages have failed to build, maybe you can check that too?

Thanks!

**Comment by troyready** [comment]
Same experience here (and my python-oauth2 system package still seems to be installed)

**Comment by amsz** [comment]
I have same problem, and run 'sudo pip install py-oauth2', the error log change to:

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2311, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2017, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 8, in <module>
    from everpad.pad.editor import Editor
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/**init**.py", line 9, in <module>
    from everpad.pad.editor.content import ContentEdit
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 143, in <module>
    class ContentEdit(QObject):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 150, in ContentEdit
    _html = open(_editor_path).read()
IOError: [Errno 2] No such file or directory: '/usr/lib/pymodules/python2.7/share/everpad/editor.html'

---

use Ubuntu12.10 and latest ppa version.

**Comment by JanStevens** [comment]
Using Ubuntu 12.04 same error as hotice, then reinstalled everpad and now my everpad-lens keeps crashing...

**Comment by BlackDex** [comment]
Same problems here.
No everpad any more :(.

**Comment by nvbn** [comment]
I'm testing automatic package building and something goes wrong.
Fixed packages pushed to ppa.

**Comment by hotice** [comment]
It still doesn't work with the new version:

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2013, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 8, in <module>
    from everpad.pad.editor import Editor
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/**init**.py", line 9, in <module>
    from everpad.pad.editor.content import ContentEdit
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 143, in <module>
    class ContentEdit(QObject):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 150, in ContentEdit
    _html = open(_editor_path).read()
IOError: [Errno 2] No such file or directory: 'usr/share/everpad/editor.html'

**Comment by johannestoger** [comment]
Is this connected to #262 ?

**Comment by hotice** [comment]
The latest package uploaded to the PPA fixes this. Thanks!

**Comment by BlackDex** [comment]
Thx it is fixed indeed :).

**Comment by nvbn** [comment]
Good =)

**Comment by amsz** [comment]
Thank you ~

**Comment by tdubourg** [comment]
I can confirm that the bug is still present :

```
% everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 8, in <module>
    from everpad.pad.editor import Editor
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/__init__.py", line 9, in <module>
    from everpad.pad.editor.content import ContentEdit
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 132, in <module>
    class ContentEdit(QObject):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 139, in ContentEdit
    _html = open(_editor_path).read()
IOError: [Errno 2] No such file or directory: '/usr/lib/pymodules/python2.7/share/everpad/editor.html'
```

And I just freshly installed the package on Ubuntu 12.04 LTS from the PPA indicated in the Readme.

The problem is that `/usr/lib/pymodules/python2.7/share/everpad` should be `/usr/share/everpad`, in order for it to work, on my own machine I juste dirty symlinked `/usr/lib/pymodules/python2.7/share` to `/usr/share` but it for sure is not the right fix for this issue :)

**Comment by pehlm** [comment]
Have this issue too after upgrade to 2.5.5. Not wanting to symlink /usr/lib/pymodules/python2.7/share to /usr/share though ;)

**Comment by skorasaurus** [comment]
@tdubourg I installed yesterday, same system and package (2.5.5-0~precise) as you and received the same error. Today, I updated to 2.5.6-0~precise and no have that error.

**Comment by magowiz** [comment]
the issue came back in last released ubuntu package : 2.6.0 in ubuntu 13.10 saucy on x64

$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2805, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 696, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PySide

**Comment by guillermolisi** [comment]
Same issue here !

Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PySide

Ubuntu 12.04.3 amd64  up to date.
Before the last update, today morning, Everpad runs very good !
